### ISSUE TITLE
Match "Genus sp." identifications

### ISSUE THREAD

**Issue by rubysaltbush** [traitecoevo/ausflora#3]
Currently it looks like a large number of unmatched species from my dataset are genus-level identifications (i.e. Senna sp.). This makes sense given the APC search itself currently doesn't return anything for sp.'s, unless you give it something explicitly genus only. 

<img width="820" alt="Screen Shot 2020-09-03 at 8 27 49 am" src="https://user-images.githubusercontent.com/68254917/92043483-7541bb80-edbf-11ea-83f5-2b656d35422d.png">

Is it possible to convert "Genus sp." searches to genus-level searches and return a genus-level value for them, such that e.g. a Dryandra sp. entry would be returned as Banksia sp.?

**Comment by dfalster** [comment]
Certainly possible. 

In the current version [we ignore anything ending in sp.](https://github.com/traitecoevo/apcnames/blob/b169266255397530821bbece9c63d36837eb3cc6/R/clean_names.R#L111). This is because there are a lot of records in the APC and APNI called something like `... sp.` that then resolve to a particular species, not a generic species of that genus. 

But I agree we should check the genus and update, as you suggest.
